### ISSUE TITLE
Login Credentials

### ISSUE THREAD

**Issue by dannyvoid** [tobe81cwb/instaripper#1]
Would adding login capabilities be possible for this? With InstaRaider I just used my firefox profile, but this is an entirely different situation without Selenium.

**Comment by tobe81cwb** [comment]
Yes, it's possible. I will update the code (maybe tomorrow) with this feature. I don't like this, because "InstaRipper is a Instagram archiving tool that downloads all photos and videos for any **public** Instagram account...", but I will add the feature.
